Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from cvedata.ms_feed_kbs import get_ms_kb_to_bins_json
from cvedata.winbindex import get_winbindex_kbs_to_bin_map
from cvedata.msrc_pandas import get_msrc_cvrf_pandas_df
import pandas as pd

wb_kbs = get_winbindex_kbs_to_bin_map()
ms_kbs = get_ms_kb_to_bins_json()
msrc_pandas = get_msrc_cvrf_pandas_df()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
File [0;32m/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/cvedata/util.py:16[0m, in [0;36mget_file_json[0;34m(path, base)[0m
[1;32m     15[0m [38;5;28;01mif[39;00m path[38;5;241m.[39mname[38;5;241m.[39mendswith([38;5;124m"[39m[38;5;124m.gz[39m[38;5;124m"[39m):
[0;32m---> 16[0m     [38;5;28;01mwith[39;00m [43mgzip[49m[38;5;241;43m.[39;49m[43mopen[49m[43m([49m[43mpath[49m[43m)[49m [38;5;28;01mas[39;00m f:
[1;32m     17[0m         [38;5;28;01mreturn[39;00m json[38;5;241m.[39mload(f)

File [0;32m/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/gzip.py:58[0m, in [0;36mopen[0;34m(filename, mode, compresslevel, encoding, errors, newline)[0m
[1;32m     57[0m [38;5;28;01mif[39;00m [38;5;28misinstance[39m(filename, ([38;5;28mstr[39m, [38;5;28mbytes[39m, os[38;5;241m.[39mPathLike)):
[0;32m---> 58[0m     binary_file [38;5;241m=[39m [43mGzipFile[49m[43m([49m[43mfilename[49m[43m,[49m[43m [49m[43mgz_mode[49m[43m,[49m[43m [49m[43mcompresslevel[49m[43m)[49m
[1;32m     59[0m [38;5;28;01melif[39;00m [38;5;28mhasattr[39m(filename, [38;5;124m"[39m[38;5;124mread[39m[38;5;124m"[39m) [38;5;129;01mor[39;00m [38;5;28mhasattr[39m(filename, [38;5;124m"[39m[38;5;124mwrite[39m[38;5;124m"[39m):

File [0;32m/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/gzip.py:174[0m, in [0;36mGzipFile.__init__[0;34m(self, filename, mode, compresslevel, fileobj, mtime)[0m
[1;32m    173[0m [38;5;28;01mif[39;00m fileobj [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[0;32m--> 174[0m     fileobj [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mmyfileobj [38;5;241m=[39m [43mbuiltins[49m[38;5;241;43m.[39;49m[43mopen[49m[43m([49m[43mfilename[49m[43m,[49m[43m [49m[43mmode[49m[43m [49m[38;5;129;43;01mor[39;49;00m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43mrb[39;49m[38;5;124;43m'[39;49m[43m)[49m
[1;32m    175[0m [38;5;28;01mif[39;00m filename [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/cvedata/data/winbindex-kb-to-bins-map.json.gz'

The above exception was the direct cause of the following exception:

[0;31mException[0m                                 Traceback (most recent call last)
Cell [0;32mIn [1], line 6[0m
[1;32m      3[0m [38;5;28;01mfrom[39;00m [38;5;21;01mcvedata[39;00m[38;5;21;01m.[39;00m[38;5;21;01mmsrc_pandas[39;00m [38;5;28;01mimport[39;00m get_msrc_cvrf_pandas_df
[1;32m      4[0m [38;5;28;01mimport[39;00m [38;5;21;01mpandas[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpd[39;00m
[0;32m----> 6[0m wb_kbs [38;5;241m=[39m [43mget_winbindex_kbs_to_bin_map[49m[43m([49m[43m)[49m
[1;32m      7[0m ms_kbs [38;5;241m=[39m get_ms_kb_to_bins_json()
[1;32m      8[0m msrc_pandas [38;5;241m=[39m get_msrc_cvrf_pandas_df()

File [0;32m/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/cvedata/winbindex.py:190[0m, in [0;36mget_winbindex_kbs_to_bin_map[0;34m()[0m
[1;32m    189[0m [38;5;28;01mdef[39;00m [38;5;21mget_winbindex_kbs_to_bin_map[39m():
[0;32m--> 190[0m     [38;5;28;01mreturn[39;00m [43mget_file_json[49m[43m([49m[43mWINDOWS_KBS_TO_BINS_PATH[49m[43m,[49m[38;5;18;43m__file__[39;49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/cvedata/util.py:22[0m, in [0;36mget_file_json[0;34m(path, base)[0m
[1;32m     20[0m             [38;5;28;01mreturn[39;00m json[38;5;241m.[39mload(f)
[1;32m     21[0m [38;5;28;01mexcept[39;00m [38;5;167;01mFileNotFoundError[39;00m [38;5;28;01mas[39;00m e:
[0;32m---> 22[0m     [38;5;28;01mraise[39;00m [38;5;167;01mException[39;00m(
[1;32m     23[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;124mMissing [39m[38;5;132;01m{[39;00mpath[38;5;132;01m}[39;00m[38;5;124m. [39m[38;5;130;01m\n[39;00m[38;5;124mPlease run [39m[38;5;132;01m{[39;00mbase[38;5;132;01m}[39;00m[38;5;124m or download release data: python -m cvedata.download[39m[38;5;124m"[39m) [38;5;28;01mfrom[39;00m [38;5;21;01me[39;00m

[0;31mException[0m: Missing /opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/cvedata/data/winbindex-kb-to-bins-map.json.gz. 
Please run /opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/cvedata/winbindex.py or download release data: python -m cvedata.download
Exception: Missing /opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/cvedata/data/winbindex-kb-to-bins-map.json.gz. 
Please run /opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/cvedata/winbindex.py or download release data: python -m cvedata.download

