Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
tags = get_msrc_tags_freq()
titles = get_msrc_titles()

win10_sys32_ver = get_verinfo_desc_to_bins_json()
wb_ver_ver = get_winbindex_desc_to_bin_map()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
File [0;32m/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/cvedata/util.py:19[0m, in [0;36mget_file_json[0;34m(path, base)[0m
[1;32m     18[0m [38;5;28;01melse[39;00m:
[0;32m---> 19[0m     [38;5;28;01mwith[39;00m [38;5;28;43mopen[39;49m[43m([49m[43mpath[49m[43m)[49m [38;5;28;01mas[39;00m f:
[1;32m     20[0m         [38;5;28;01mreturn[39;00m json[38;5;241m.[39mload(f)

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/cvedata/data/msrc-tags-merged-frequency.json'

The above exception was the direct cause of the following exception:

[0;31mException[0m                                 Traceback (most recent call last)
Cell [0;32mIn [2], line 1[0m
[0;32m----> 1[0m tags [38;5;241m=[39m [43mget_msrc_tags_freq[49m[43m([49m[43m)[49m
[1;32m      2[0m titles [38;5;241m=[39m get_msrc_titles()
[1;32m      4[0m win10_sys32_ver [38;5;241m=[39m get_verinfo_desc_to_bins_json()

File [0;32m/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/cvedata/msrc_pandas.py:389[0m, in [0;36mget_msrc_tags_freq[0;34m()[0m
[1;32m    388[0m [38;5;28;01mdef[39;00m [38;5;21mget_msrc_tags_freq[39m():
[0;32m--> 389[0m     [38;5;28;01mreturn[39;00m [43mget_file_json[49m[43m([49m[43mMSRC_TAGS_FREQ_PATH[49m[43m,[49m[43m [49m[38;5;18;43m__file__[39;49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/cvedata/util.py:22[0m, in [0;36mget_file_json[0;34m(path, base)[0m
[1;32m     20[0m             [38;5;28;01mreturn[39;00m json[38;5;241m.[39mload(f)
[1;32m     21[0m [38;5;28;01mexcept[39;00m [38;5;167;01mFileNotFoundError[39;00m [38;5;28;01mas[39;00m e:
[0;32m---> 22[0m     [38;5;28;01mraise[39;00m [38;5;167;01mException[39;00m(
[1;32m     23[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;124mMissing [39m[38;5;132;01m{[39;00mpath[38;5;132;01m}[39;00m[38;5;124m. [39m[38;5;130;01m\n[39;00m[38;5;124mPlease run [39m[38;5;132;01m{[39;00mbase[38;5;132;01m}[39;00m[38;5;124m or download release data: python -m cvedata.download[39m[38;5;124m"[39m) [38;5;28;01mfrom[39;00m [38;5;21;01me[39;00m

[0;31mException[0m: Missing /opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/cvedata/data/msrc-tags-merged-frequency.json. 
Please run /opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/cvedata/msrc_pandas.py or download release data: python -m cvedata.download
Exception: Missing /opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/cvedata/data/msrc-tags-merged-frequency.json. 
Please run /opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/cvedata/msrc_pandas.py or download release data: python -m cvedata.download

